<a href="https://colab.research.google.com/github/Gail529/chess_ML/blob/main/feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Required Libraries

In [66]:
!pip install category_encoders

     |████████████████████████████████| 81kB 6.6MB/s 


In [69]:
%matplotlib inline
import warnings
import category_encoders as ce
from category_encoders.hashing import HashingEncoder
from category_encoders.binary import BinaryEncoder
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder 

# Checking the distribution of the data

In [75]:
data=pd.read_csv('/content/games.csv')


In [78]:
print(data.shape)
data.head()


(20058, 9)


rated  turns victory_status  ... black_rating opening_eco  opening_ply
0  False     13      outoftime  ...         1191         D10            5
1   True     16         resign  ...         1261         B00            4
2   True     61           mate  ...         1500         C20            3
3   True     61           mate  ...         1454         D02            3
4   True     95           mate  ...         1469         C41            5

[5 rows x 9 columns]

In [77]:
data.columns
del data['id']
del data['created_at']
del data['last_move_at']
del data['white_id']
del data['black_id']
del data['opening_name']
del data['moves']


In [79]:
data['rating_diff'] = data['white_rating']-data['black_rating']
data.columns

Index(['rated', 'turns', 'victory_status', 'winner', 'increment_code',
       'white_rating', 'black_rating', 'opening_eco', 'opening_ply',
       'rating_diff'],
      dtype='object')

In [ ]:
data.dtypes

In [ ]:
data.describe()

In [44]:
#Scaling continous variables 
#standardisation
from sklearn import preprocessing 
cols=['turns','white_rating', 'black_rating', 'opening_ply']
cols_to_scale=data[cols]
Standardisation = preprocessing.StandardScaler()  
scaled_cols= Standardisation.fit_transform(cols_to_scale) 
print ("\nStandardised columns : \n", scaled_cols) 


Standardised columns : 
 [[-1.4139516  -0.33178766 -1.36698461  0.0654322 ]
 [-1.32458542 -0.94295461 -1.12645864 -0.29208323]
 [ 0.01590722 -0.34552175 -0.30523428 -0.64959865]
 ...
 [-0.75859964 -1.2966074  -1.04055651 -0.64959865]
 [ 1.44576604 -0.81248077 -1.24328554 -0.29208323]
 [ 0.52231555 -1.24167104 -0.858444   -0.64959865]]


In [45]:
#Scaling continous variables 
#min max scaling
cols=['turns','white_rating', 'black_rating', 'opening_ply']
cols_to_scale=data[cols]
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1)) 
scaled_cols = min_max_scaler.fit_transform(cols_to_scale) 
  
print ("\nAfter min max Scaling : \n", scaled_cols) 



After min max Scaling : 
 [[0.03448276 0.3736952  0.20785936 0.14814815]
 [0.04310345 0.28079332 0.24405377 0.11111111]
 [0.17241379 0.37160752 0.36763185 0.07407407]
 ...
 [0.09770115 0.22703549 0.25698035 0.07407407]
 [0.31034483 0.3006263  0.22647363 0.11111111]
 [0.22126437 0.23538622 0.28438469 0.07407407]]


In [82]:
# label encoding the data 
categorical_feature_mask = data.dtypes==object
# filter categorical columns using mask and turn it into a list
categorical_cols = data.columns[categorical_feature_mask].tolist()
print(categorical_cols)
le = LabelEncoder() 
data['winner']= le.fit_transform(data['winner'])
data['rated']= le.fit_transform(data['rated'])
data['victory_status']= le.fit_transform(data['rated'])

#for categorical_cols with high cardinality
encoder= ce.BinaryEncoder(cols=['increment_code','opening_eco'])
data_encoded=encoder.fit_transform(data) 
data_encoded



['increment_code', 'opening_eco']


/usr/local/lib/python3.6/dist-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


rated  turns  victory_status  ...  opening_eco_9  opening_ply  rating_diff
0          0     13               0  ...              1            5          309
1          1     16               1  ...              0            4           61
2          1     61               1  ...              1            3           -4
3          1     61               1  ...              0            3          -15
4          1     95               1  ...              1            5           54
...      ...    ...             ...  ...            ...          ...          ...
20053      1     24               1  ...              0            2          471
20054      1     82               1  ...              0            2           37
20055      1     35               1  ...              1            3          -67
20056      1    109               1  ...              0            4          133
20057      1     78               1  ...              1            3         -104

[20058 rows x 28 columns]